import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    searchRides: 'Search Rides',
    myTrips: 'My Trips',
    upcomingTrips: 'Upcoming Trips',
    previousTrips: 'Previous Trips',
    noUpcomingTrips: 'No upcoming trips found',
    noPreviousTrips: 'No previous trips found',
    transactionHistory: 'Transaction History',
    profile: 'Profile',
    logout: 'Logout',
    brandName: 'D-Ride',
    howItWorks: 'How It Works',
    features: 'Features',
    routes: 'Routes',
    partners: 'Partners',
    contactUs: 'Contact Us',
    signIn: 'Sign In',
    getStarted: 'Get Started',
    signOut: 'Sign Out',
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    noNotifications: 'No new notifications',

    // Search Page
    whereTo: 'Where are we going today?',
    pickupPlaceholder: 'Search pickup stop (e.g. Maadi)...',
    dropoffPlaceholder: 'Search dropoff stop (e.g. Smart Village)...',
    findRides: 'Find Available Minibuses',
    routePath: 'Route path',
    departureTime: 'Departure Time',
    price: 'Price',
    bookSeat: 'Choose Seats & Checkout',
    noRides: 'No available rides found for this route.',

    // Seat / Checkout Page
    seatSelectionTitle: 'Toyota HiAce Seat Selection',
    fleetDesc: 'Cairo Commuter Minibus Fleet (14-Seater)',
    bookingSummary: 'Booking Summary',
    routeLabel: 'Route',
    departureLabel: 'Departure',
    boardingCp: 'Boarding Checkpoint 📍',
    boardingCpDesc: "Choose where the driver should pick you up. We've highlighted the closest checkpoint to you.",
    selectedPickup: 'Selected Pickup',
    selectSeats: 'Select Your Seats',
    availableLegend: 'Available',
    selectedLegend: 'Selected',
    occupiedLegend: 'Occupied',
    luggageLegend: 'Luggage Hold',
    selectedSlots: 'Selected Slots',
    paymentMethod: 'Payment Method 💳',
    cardPayment: '💳 Card',
    walletPayment: '📱 Wallet',
    cashPayment: '💵 Cash',
    walletInputLabel: 'Mobile Wallet Number (Vodafone, Orange, Etisalat Cash)',
    walletInputPlaceholder: 'e.g. 01012345678',
    walletInputDesc: 'Standard 11-digit Egyptian mobile number.',
    cashDesc: '🤝 Cash on Board: Pay directly to the minibus driver during boarding. Ticket confirmation is instant.',
    totalFare: 'Total Fare',
    processingPay: 'Processing Securely...',
    confirmCash: 'Confirm Booking (Cash)',
    payViaPaymob: 'Pay {amount} EGP via Paymob',
    securedPay: 'Secured via Paymob Egypt. Cards, Wallets, and Cash on Board supported.',

    // My Trips Page
    yourCommuteBadge: 'Your Commute',
    tripCancelled: 'Trip Cancelled',
    myBookingsTitle: 'My Bookings & Boarding Passes',
    myBookingsSub: 'Scan mock tickets or track your driver live on Egypt\'s premier mass-transit network.',
    noTickets: 'No Tickets Found',
    startBooking: 'Once you book your first ride, your boarding pass will appear here. Start by searching for a route.',
    dateLabel: 'Date',
    departureLabelShort: 'Departure',
    seatLabelShort: 'Seat',
    fareLabelShort: 'Fare',
    boardingCPShort: 'Boarding CP',
    scanQrHelper: 'Scan Ticket QR at Boarding',
    passId: 'PASS ID',
    optionsBtn: 'Options',
    telemetryTitle: 'Ride Telemetry & Dossier',
    secureSystem: 'SECURE SYSTEM',
    driverLabel: 'Driver',
    vehicleLabel: 'Vehicle',
    statusLabel: 'Status',
    trackLive: 'Track Live 📍',
    cancelSeat: 'Cancel Seat',
    payNow: 'Pay Now',
    backBtn: 'Back',
    boardingPassQrTitle: 'Boarding Pass QR 🎫',
    boardingPassQrDesc: 'Present this QR code to the D-Ride driver upon boarding the minibus.',
    ticketId: 'Ticket ID',
    verificationStatus: 'Verification Status',
    statusBoarded: 'Boarded & Checked In ✅',
    statusReady: 'Ready to Board 🕒',

    // RouteSearchForm & Home Autocomplete
    detectStation: 'Detect Station',
    detectingLocation: '⏳ Detecting your location...',
    gpsNotSupported: '⚠️ Geolocation is not supported by your browser',
    noStationsDefined: '⚠️ No stations defined in the platform currently.',
    matchedNearestStation: '📍 Matched nearest station: {name} in {city} ({distance} km away)',
    failedToRetrieveLocation: '⚠️ Failed to retrieve location: {message}',
    selectOnMap: 'Select on Map',
    whereAreYouBoarding: 'Where are you boarding?',
    searchBoardingStopPlaceholder: 'Search boarding stop...',
    noMatchingStations: 'No matching stations',
    whereAreYouGoing: 'Where are you going?',
    selectBoardingStopFirst: 'Select boarding stop first',
    searchDestinationStopPlaceholder: 'Search destination stop...',
    noReachableStopsFound: 'No reachable stops found',
    travelDateLabel: 'Travel Date',
    numberOfSeatsLabel: 'Number of Seats',
    seatCountSingular: '{count} Seat',
    seatCountPlural: '{count} Seats',
    roundTripLabel: 'Return Trip',
    returnDateLabel: 'Return Date',
    step1of2: 'Step 1 of 2: Select Outbound Trip',
    step2of2: 'Step 2 of 2: Select Return Trip',
    showTripsBtn: 'Show Trips',
    browseRoutesManually: 'Or browse all routes manually →',
    selectPickupLocationOnMap: 'Select Pickup Location on Map',
    dragPinToPickupPoint: 'Drag this pin to your pickup point',
    nearestMatchedStationMap: 'Nearest Matched Station',
    metersAway: 'meters away',
    route: 'Route',
    noStationsFoundNearbyMap: '⚠️ No stations found nearby.',
    cancelBtn: 'Cancel',
    confirmPickupStationBtn: 'Confirm Pickup Station',

    // Hero Section
    liveRouteTelemetryBadge: 'Live Route Telemetry Enabled',
    heroTitlePart1: 'The Elite',
    heroTitlePart2: 'Way to',
    heroTitleAccent: 'Travel.',
    heroSubtitle: 'Redefining your Trip from Cairo and Alexandria. Powered by Destination, D-Ride combines speed, privacy, and premium comfort, featuring memory foam seating and enhanced security to elevate every mile of your trip.',
    bookARideBtn: 'Book a Ride',
    learnMoreBtn: 'Learn More →',
    findYourRouteCardTitle: 'Find Your Route',
    selectYourDestinationCardSub: 'Select your destination',

    // Stats
    dailyRoutesVal: '150+',
    dailyRoutesLbl: 'Daily Routes',
    happyRidersVal: '50K+',
    happyRidersLbl: 'Happy Riders',
    vehiclesVal: '200+',
    vehiclesLbl: 'Vehicles',
    avgRatingVal: '4.8⭐',
    avgRatingLbl: 'Avg Rating',

    // How It Works
    simpleAndFast: 'Simple & Fast',
    howItWorksTitle: 'How It Works',
    howItWorksDesc: 'Get from A to B in three simple steps. No haggling, no uncertainty — just a smooth, reliable commute.',
    step1Title: 'Search',
    step1Desc: 'Enter your pickup and destination. We\'ll show you the best available routes with live ETAs.',
    step2Title: 'Book',
    step2Desc: 'Select your preferred trip and pay securely through our integrated Paymob checkout. Instant confirmation.',
    step3Title: 'Ride',
    step3Desc: 'Track your bus in real-time, board with your digital ticket, and enjoy a comfortable air-conditioned ride.',

    whyDride: 'Why D-Ride',
    builtForCairoStreets: 'Built for Cairo\'s Streets',
    builtForCairoStreetsDesc: 'We understand the Egyptian commute. That\'s why every feature is designed to make your daily journey better.',
    featureLiveTrackingTitle: 'Live Tracking',
    featureLiveTrackingDesc: 'Peace of mind for you and your family. Real-time updates ensure total safety throughout your journey.',
    featureMemoryFoamTitle: 'Memory Foam Seating',
    featureMemoryFoamDesc: 'An exclusive experience. Designed for premium support and unmatched comfort, only at D-Ride.',
    featureUsbTitle: 'USB',
    featureUsbDesc: 'Stay connected. A dedicated charging port for every passenger to power your journey',
    featureSpaciousComfortTitle: 'Spacious Comfort',
    featureSpaciousComfortDesc: 'Extra legroom and safety-certified seatbelts, designed to give you the personal space you deserve.',
    featureDashCamTitle: 'Dash Cam',
    featureDashCamDesc: 'Your security is our priority. Every trip is monitored to ensure the highest standards of safety.',

    // Partners
    trustedCollaborations: 'Trusted Collaborations',
    ourPartnersTitle: 'Our Partners',
    partnersSub: 'We work in partnership with Egypt\'s leading organizations, universities, and payment networks to deliver a seamless journey.',

    // Footer
    operatedBy: 'Operated by Destination',
    about: 'About',
    terms: 'Terms',
    privacy: 'Privacy',
    contact: 'Contact',
    allRightsReserved: '© 2026 D-Ride. All rights reserved.',

    // Auth Page - Login
    loginTitle: 'Sign In to D-Ride',
    loginSubtitle: 'Enter your credentials to manage your commutes and book seats.',
    loginEmailLabel: 'Email Address',
    loginEmailPlaceholder: 'e.g. ahmed@example.com',
    loginPasswordLabel: 'Password',
    loginPasswordPlaceholder: '••••••••',
    loginBtn: 'Sign In',
    loggingIn: 'Signing in securely...',
    dontHaveAccount: 'Don\'t have an account?',
    signUpNow: 'Sign up now',
    invalidCredentials: 'Login failed. Please check your credentials.',
    
    // Auth Page - Register
    registerTitle: 'Create Passenger Account',
    registerSubtitle: 'Join Egypt\'s premium commuter minibus network today.',
    registerNameLabel: 'Full Name',
    registerNamePlaceholder: 'e.g. Ahmed Hassan',
    registerPhoneLabel: 'Egyptian Mobile Number',
    registerPhonePlaceholder: 'e.g. 01012345678',
    registerBtn: 'Create Account',
    registering: 'Creating account securely...',
    alreadyHaveAccount: 'Already have an account?',
    signInNow: 'Sign in now',
    registerFailed: 'Registration failed. Please check details.',
    phoneMustBe11: 'Egyptian phone number must be exactly 11 digits.',

    // Checkout Details & Page
    boardingAndDropoffTitle: 'Boarding & Dropoff Checkpoints',
    verifyStopsHelper: 'Verify or select where the driver should pick you up and drop you off. Click markers or dots to adjust.',
    showMapBtn: 'Show Map',
    selectManuallyBtn: 'Select Manually',
    manualSelectionFallback: 'Manual Selection Fallback',
    manualSelectionFallbackDesc: 'Select primary Cairo transit hubs below to map them to your route stops:',
    manualPickupHubLabel: 'Manual Pickup Hub',
    manualDropoffHubLabel: 'Manual Dropoff Hub',
    selectPickupOption: 'Select Pickup',
    selectDropoffOption: 'Select Dropoff',
    cabinLayoutTitle: 'Toyota HiAce Cabin Layout',
    cabinLayoutDesc: 'Click available seats to select them. Locked seats are reserved for luggage.',
    hiaceModelLabel: 'Toyota HiAce L2H2',
    selectRequiredSeatsWarning: 'Please select exactly {count} seat(s) to match your search request.',
    confirmBookingBtn: 'Confirm Booking',
    configureCommuteStepper: 'Configure Commute',
    selectPaymentStepper: 'Select Payment',
    confirmSeatStepper: 'Confirm Seat',
    loadingTripConfig: 'Loading trip configuration...',
    noTripSelected: 'No trip selected.',
    vipCockpitSeat: 'Front VIP Cockpit Seat ⭐',
    vipCockpitSeatDesc: 'Front-row seat with scenic dashboard views next to the driver!',
    premiumWindowSeat: 'Premium Window Seat 🪟',
    premiumWindowSeatDesc: 'Window-side seat with scenic community views.',
    rearWindowSeat: 'Rear Window Seat 🪟',
    rearWindowSeatDesc: 'Comfortable window seat on the rear row.',
    spaciousAisleSeat: 'Spacious Aisle Seat 🚶',
    spaciousAisleSeatDesc: 'Easy-access seat located directly on the cabin aisle.',
    standardCabinSeat: 'Standard Cabin Seat 💺',
    standardCabinSeatDesc: 'Comfortable mid-cabin passenger seat.',
    luggageHoldAreaLocked: 'Luggage Hold Area (Locked by Admin)',
    seatOccupiedTitle: 'Seat #{num} (Occupied)',
    seatTitle: 'Seat #{num}',
    pleaseSelectSeatsToMatch: 'Please select exactly {count} seat(s) to match your search request.',
    reservationFailed: 'Reservation failed: ',
    closestPickupHighlighted: "We've highlighted the closest checkpoint to you.",
    requestedSeatsLabel: 'Requested Seats',
    requestedSeatsCountLabel: '{count} of {required} Selected',
    dashboardLabel: 'Dashboard',
    slidingDoorEntryLabel: 'Sliding door entry',
    commuteDetailsLabel: 'Commute Details',
    lineRouteLabel: 'Line Route',
    localizedBoardingTimeLabel: 'Localized Boarding Time',
    notSelectedLabel: 'Not Selected',
    bookingMultipleSeatsDesc: 'Booking multiple spaces in a single transaction. All boarding passes will be dispatched simultaneously!',
    invoiceBreakdownLabel: 'Invoice Breakdown',
    legSegmentLabel: 'Leg Segment',
    startLabel: 'Start',
    endLabel: 'End',
    baseFareLabel: 'Base Fare',
    bookingFeeLabel: 'Booking Fee',
    reservingSeatsLoading: 'Reserving Seats...',
    selectRequiredSeatsButton: 'Select exactly {count} seat(s)',
    confirmAndProceedBtn: 'Confirm & Proceed to Payment',
    seatsTemporaryHoldInfo: 'Seats will be temporarily held for 10 minutes.',
    tripConfigNotFound: 'Trip configuration not found.',

    invalidMobileWalletNumber: 'Please enter a valid Egyptian mobile wallet number (e.g. 01012345678)',

    // Support Chat Widget
    supportHelpDesk: 'D-Ride Help Desk',
    supportOnlineStatus: 'Online / Available 24/7',
    supportLiveChatStatus: 'Real-time Live Chat',
    supportTicketSelectionDesc: 'Select an active ticket to chat directly with our dispatch operators:',
    supportNoActiveTickets: 'No active support tickets found.',
    supportCreateTicketBtn: 'Create Support Ticket',
    supportNeedNewTicketPrompt: 'Need to open a new ticket?',
    supportOriginalTicketCardHeader: 'Original Issue Ticket',
    supportStartChattingPlaceholder: 'No messages in this chat yet. Start the conversation!',
    supportTicketClosedResolved: 'This support ticket has been resolved.',
    supportTypeMessagePlaceholder: 'Type message...',

    // TripSearch & Available Trips Page
    availableTrips: 'Available Trips',
    smartSearchSubtitle: 'Smart Search: Pickups & Dropoffs within 5km',
    next5days: 'Next 5 Days',
    searchingRides: 'Searching for the best rides...',
    noTripsFound: 'No trips found',
    noTripsFoundDesc: "We couldn't find any scheduled trips for the selected dates.",
    searchAnotherRoute: 'Search Another Route',
    earliest: 'Earliest',
    cheapest: 'Cheapest',
    fewestWalks: 'Fewest Walks',
    activeShuttle: 'Active Shuttle',
    alternativeDate: 'Alternative Date',
    boardingStop: 'Boarding Stop',
    dropoffStop: 'Dropoff Stop',
    walksTotal: 'Walks: {total}m total ({pickup}m to pickup · {dropoff}m from dropoff)',
    seatsLeft: '{count} seats left',
    bookSeatTicket: 'Book Seat 🎟️',
    routeStopsSelect: 'Route Stops (Select stops)',
    pickup: 'Pickup',
    dropoff: 'Dropoff',
    noSearchParameters: 'No Search Parameters',
    noSearchParametersDesc: 'Please go back and select a route or enter your location to search for trips.',
    backToHome: 'Back to Home',

    // Payment Page Secure & Costs
    secureRidePayment: 'Secure Ride Payment',
    secureRidePaymentDesc: 'Secure Ride Payment Gateway',
    selectPaymentMethod: 'Select Payment Method',
    pciDssHelper: 'All transaction gateways are end-to-end encrypted and comply with PCI-DSS standards.',
    creditCardOptionTitle: 'Credit Card / Debit Card',
    creditCardOptionDesc: 'Pay online instantly using Visa, Mastercard, or Meeza via the secure Paymob gateway.',
    cashOptionTitle: 'Cash on Board',
    cashOptionDesc: 'Pay cash directly to the driver upon boarding. Note that ticket reservations are still instant.',
    securePaymobCheckout: 'Secure Paymob Checkout',
    paymobRedirectionDisclaimer: 'You will be redirected to the secure Paymob processing page to enter card details.',
    supportedCardSchemes: 'Supported schemes: Visa, Mastercard, Meeza, and international bank cards.',
    cashOnBoardInstructions: 'Please prepare exact change of {amount} EGP if possible to avoid delays during boarding check-in.',
    reservationDossier: 'Reservation Dossier',
    routeLineLabel: 'Route Line',
    standardRoute: 'Standard Route',
    departureSchedule: 'Departure Schedule',
    assignedSeats: 'Assigned Seats',
    pickupHub: 'Pickup Hub',
    dropoffHub: 'Dropoff Hub',
    billingDetails: 'Billing Details',
    seatReservationCost: 'Seat Reserv. ({count})',
    vatIncluded: 'VAT (14% Included)',
    processingFee: 'Processing Fee',
    freeProcessing: '0.00 EGP (FREE)',
    totalCharge: 'Total Charge',
    encryptedOnlineCheckoutInfo: 'Encrypted online checkouts. Cards and Cash accepted.',
    bookingDetailsNotFound: 'Booking details not found.',
    returnToHome: 'Return to Home',
    noBookingSelected: 'No booking selected.',
    loadingBookingDetails: 'Loading booking details...',
    verifyingPayment: 'Verifying payment...',
    paymentSuccessful: 'Payment Successful!',
    paymentSuccessDesc: 'Your transaction has been processed and your seat is confirmed.',
    viewMyTrips: 'View My Trips',
    paymentFailed: 'Payment Failed',
    paymentFailedDesc: 'We could not process your payment. Please try again.',
    paymentSuccessNotificationTitle: 'Payment Successful ✅',
    paymentSuccessNotificationDesc: 'Your transaction was completed and your seat is secured.',
    promoCodeLabel: 'Promo Code',
    applyPromoCode: 'Apply',
    removePromoCode: 'Remove',
    promoCodeApplied: 'Promo code applied successfully!',
    promoCodeInvalid: 'Invalid or expired promo code',
    promoDiscount: 'Discount ({code})',
    enterPromoCode: 'Enter promo code...',
    
    // LiveTracking Page
    noVehicleSelected: 'No Vehicle Selected',
    selectTripToTrack: 'Please select a trip from your bookings to track.',
    backToMyTrips: 'Back to My Trips',
    activeGpsTracking: 'Active GPS Tracking',
    vehicleOffline: 'Vehicle Offline',
    statusScheduled: 'Scheduled',
    loadingRoute: 'Loading Route...',
    scheduledDeparture: 'Scheduled Departure:',
    minibusDetailsWillUpdate: 'Minibus details will update soon. The driver has not started broadcasting live GPS location yet. This usually starts 10-15 minutes prior to departure when the boarding gates open.',
    minibusOnRoute: 'Minibus is on route. Tracking coordinates broadcasted smoothly.',
    vehicleModel: 'Vehicle Model:',
    licensePlate: 'License Plate:',
    driverPartner: 'Driver Partner:',
    callOperator: 'Call Operator',
    supportChat: 'Support Chat',
    supportTicketCreatedAlert: 'Support ticket created. D-Ride support agent will contact you shortly.',
    departureTerminal: 'Departure Terminal',
    destinationStation: 'Destination Station',
    shuttleActiveLocation: 'Shuttle Active Location',

    // Contact Page
    contactSupportHelpDeskBadge: 'Support & Help Desk',
    contactGetInTouch: 'Get in Touch',
    contactSubtitle: 'Have questions about your booking, payment, or routes? Drop us a line and our dedicated team will get back to you shortly.',
    contactEmailSupport: 'Email Support',
    contactPhoneHotline: 'Phone Hotline',
    contactHqLocation: 'HQ Location',
    contactHqLocationVal: 'New Cairo, Cairo, Egypt',
    contactWorkingHours: 'Working Hours',
    contactWorkingHoursVal: '24/7 Operations / Support Desk',
    contactTicketSubmitted: 'Ticket Submitted!',
    contactTicketSuccessDesc: 'Thank you for contacting D-Ride. Your ticket has been recorded, and our team will review and reply to it shortly.',
    contactSubmitAnother: 'Submit Another Ticket',
    contactOpenSupportTicket: 'Open Support Ticket',
    contactDetailIssue: 'Detail your issue and an agent will follow up.',
    contactPassengerName: 'PASSENGER NAME',
    contactEmailAddress: 'EMAIL ADDRESS',
    contactSubject: 'Subject',
    contactSubjectPlaceholder: 'e.g., Booking double billing issue',
    contactMessageDetail: 'Message Detail',
    contactMessagePlaceholder: 'Please provide details about your concern...',
    contactSubmitTicketBtn: 'Submit Ticket',
    contactSubmitting: 'Submitting...',
    contactLoadingProfile: 'Loading profile...',
    contactFailedSubmit: 'Failed to submit support ticket.',

    // Routes Page
    routesCommuteNetworks: 'Commute Networks',
    routesExplorerTitle: 'D-Ride Routes Explorer',
    routesExplorerDesc: 'Browse fixed transit lines, view custom checkpoints, see schedules, and track wait buffers. Choose a route below to view its snapped roadway coordinates and timeline.',
    routesLoading: 'Fetching Egypt commute routes...',
    routesNoRegisteredTitle: 'No Routes Registered',
    routesNoRegisteredDesc: 'There are currently no active transit routes in the system. Check back later or ask an administrator to add one.',
    routesAvailableLines: 'Available Lines ({count})',
    routesStartPrefix: '🟢 Start:',
    routesEndPrefix: '🏁 End:',
    routesNoTripsScheduled: 'No trips scheduled',
    routesTripsScheduled: '{count} trips scheduled',
    routesBookShuttles: 'Book Shuttles →',
    routesDurationMins: '{count} mins ride',
    routesBookRideBtn: 'Book Ride',
    routesInteractiveTrack: 'Interactive Transit Track',
    routesSnappedRoadways: 'Snapped Roadways (OSRM)',
    routesTimelineTitle: 'Checkpoint Sequence Timeline',
    routesOriginTerminal: 'Origin Terminal',
    routesFinalTerminal: 'Final Terminal',
    routesStopNum: 'Stop #{num}',
    routesBuffer: 'Buffer',
    routesGeofence: 'Geofence',
    routesComplianceTitle: 'Egypt Mass-Transit Compliance:',
    routesComplianceDesc: 'Buses are scheduled to wait the full wait buffer time at each checkpoint. Boarding gates close exactly at the buffer timeout. Always check your ticket geofence validation area upon boarding.'
  },
  ar: {
    // Navigation
    searchRides: 'البحث عن رحلات',
    myTrips: 'رحلاتي',
    upcomingTrips: 'الرحلات القادمة',
    previousTrips: 'الرحلات السابقة',
    noUpcomingTrips: 'لا توجد رحلات قادمة حالياً',
    noPreviousTrips: 'لا توجد رحلات سابقة',
    transactionHistory: 'سجل المعاملات',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    brandName: 'دي-رايد',
    howItWorks: 'كيف نعمل',
    features: 'المميزات',
    routes: 'المسارات',
    partners: 'شركاؤنا',
    contactUs: 'اتصل بنا',
    signIn: 'تسجيل الدخول',
    getStarted: 'ابدأ الآن',
    signOut: 'تسجيل الخروج',
    notifications: 'الإشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد إشعارات جديدة',

    // Search Page
    whereTo: 'إلى أين نحن ذاهبون اليوم؟',
    pickupPlaceholder: 'ابحث عن محطة الركوب (مثال: المعادي)...',
    dropoffPlaceholder: 'ابحث عن محطة النزول (مثال: القرية الذكية)...',
    findRides: 'البحث عن حافلات متوفرة',
    routePath: 'مسار الرحلة',
    departureTime: 'وقت المغادرة',
    price: 'السعر',
    bookSeat: 'اختر المقاعد والدفع',
    noRides: 'لم يتم العثور على رحلات متاحة لهذا المسار.',

    // Seat / Checkout Page
    seatSelectionTitle: 'حجز مقاعد تويوتا هايس',
    fleetDesc: 'أسطول حافلات القاهرة للركاب (١٤ مقعداً)',
    bookingSummary: 'ملخص الحجز',
    routeLabel: 'المسار',
    departureLabel: 'المغادرة',
    boardingCp: 'نقطة الركوب 📍',
    boardingCpDesc: 'اختر المكان الذي يجب أن يقلك السائق منه. لقد حددنا أقرب نقطة لك.',
    selectedPickup: 'نقطة الركوب المختارة',
    selectSeats: 'اختر مقاعدك',
    availableLegend: 'متاح',
    selectedLegend: 'محدد',
    occupiedLegend: 'محجوز',
    luggageLegend: 'مكان الحقائب',
    selectedSlots: 'المقاعد المحددة',
    paymentMethod: 'طريقة الدفع 💳',
    cardPayment: '💳 بطاقة',
    walletPayment: '📱 محفظة هاتف',
    cashPayment: '💵 نقداً',
    walletInputLabel: 'رقم محفظة الهاتف (فودافون، أورنج، اتصالات كاش)',
    walletInputPlaceholder: 'مثال: 01012345678',
    walletInputDesc: 'رقم هاتف محمول مصري مكون من ١١ رقماً.',
    cashDesc: '🤝 الدفع نقداً: ادفع مباشرة لسائق الحافلة عند الركوب. تأكيد التذكرة فوري.',
    totalFare: 'إجمالي الأجرة',
    processingPay: 'جاري المعالجة بأمان...',
    confirmCash: 'تأكيد الحجز (نقداً)',
    payViaPaymob: 'ادفع {amount} ج.م عبر بيموب',
    securedPay: 'مؤمن بواسطة بيموب مصر. نقبل البطاقات، محافظ الهاتف، والدفع نقداً عند الركوب.',

    // My Trips Page
    yourCommuteBadge: 'رحلاتك اليومية',
    tripCancelled: 'تم إلغاء الرحلة',
    myBookingsTitle: 'حجوزاتي وتذاكر الركوب',
    myBookingsSub: 'امسح التذاكر التجريبية أو تتبع السائق مباشرة على شبكة النقل الرائدة في مصر.',
    noTickets: 'لا توجد تذاكر حالياً',
    startBooking: 'بمجرد حجز رحلتك الأولى، ستظهر تذكرة الركوب الخاصة بك هنا. ابدأ بالبحث عن مسار.',
    dateLabel: 'التاريخ',
    departureLabelShort: 'المغادرة',
    seatLabelShort: 'المقعد',
    fareLabelShort: 'الأجرة',
    boardingCPShort: 'نقطة الركوب',
    scanQrHelper: 'امسح رمز QR عند الركوب',
    passId: 'رقم التذكرة',
    optionsBtn: 'خيارات',
    telemetryTitle: 'معلومات وتفاصيل الرحلة',
    secureSystem: 'نظام آمن',
    driverLabel: 'السائق',
    vehicleLabel: 'الحافلة',
    statusLabel: 'الحالة',
    trackLive: 'تتبع السائق مباشرة 📍',
    cancelSeat: 'إلغاء المقعد',
    payNow: 'ادفع الآن',
    backBtn: 'رجوع',
    boardingPassQrTitle: 'رمز تذكرة الركوب 🎫',
    boardingPassQrDesc: 'يرجى تقديم رمز QR هذا لسائق دي-رايد عند ركوب الحافلة.',
    ticketId: 'رقم التذكرة',
    verificationStatus: 'حالة التحقق',
    statusBoarded: 'تم صعود الحافلة والتحقق ✅',
    statusReady: 'جاهز للصعود 🕒',

    // RouteSearchForm & Home Autocomplete
    detectStation: 'تحديد أقرب محطة',
    detectingLocation: '⏳ جاري تحديد موقعك...',
    gpsNotSupported: '⚠️ تحديد الموقع الجغرافي غير مدعوم في متصفحك',
    noStationsDefined: '⚠️ لا توجد محطات معرفة حالياً',
    matchedNearestStation: '📍 تم العثور على أقرب محطة: {name} في {city} (على بعد {distance} كم)',
    failedToRetrieveLocation: '⚠️ فشل في تحديد الموقع: {message}',
    selectOnMap: 'اختر على الخريطة',
    whereAreYouBoarding: 'من أين ستركب؟',
    searchBoardingStopPlaceholder: 'ابحث عن محطة ركوب...',
    noMatchingStations: 'لا توجد محطات مطابقة',
    whereAreYouGoing: 'إلى أين تريد الذهاب؟',
    selectBoardingStopFirst: 'اختر محطة الركوب أولاً لمعرفة الوجهات المتاحة',
    searchDestinationStopPlaceholder: 'ابحث عن وجهتك...',
    noReachableStopsFound: 'لا توجد محطات تالية متاحة',
    travelDateLabel: 'تاريخ السفر',
    numberOfSeatsLabel: 'عدد المقاعد',
    seatCountSingular: 'مقعد واحد',
    seatCountPlural: '{count} مقاعد',
    roundTripLabel: 'رحلة العودة',
    returnDateLabel: 'تاريخ العودة',
    step1of2: 'الخطوة 1 من 2: اختر رحلة الذهاب',
    step2of2: 'الخطوة 2 من 2: اختر رحلة العودة',
    showTripsBtn: 'عرض الرحلات',
    browseRoutesManually: 'أو تصفح جميع المسارات يدوياً ←',
    selectPickupLocationOnMap: 'اختر موقع الركوب على الخريطة',
    dragPinToPickupPoint: 'اسحب الدبوس لتحديد موقع الركوب',
    nearestMatchedStationMap: 'أقرب محطة ركوب مطابقة',
    metersAway: 'متر',
    route: 'الخط',
    noStationsFoundNearbyMap: '⚠️ لا توجد محطات قريبة في النطاق',
    cancelBtn: 'إلغاء',
    confirmPickupStationBtn: 'تأكيد محطة الركوب',

    // Hero Section
    liveRouteTelemetryBadge: 'تم تفعيل تتبع الرحلات الحية',
    heroTitlePart1: 'رحلتك',
    heroTitlePart2: 'اليومية،',
    heroTitleAccent: 'بمنظور جديد.',
    heroSubtitle: 'وسائل نقل ذكية للقاهرة وضواحيها. احجز مقعدك في حافلات مريحة ومكيفة ذات مسارات ثابتة، وتتبع مباشر، ومدفوعات غير نقدية.',
    bookARideBtn: 'احجز رحلة',
    learnMoreBtn: 'معرفة المزيد ←',
    findYourRouteCardTitle: 'ابحث عن مسارك',
    selectYourDestinationCardSub: 'اختر وجهتك المفضلة',

    // Stats
    dailyRoutesVal: '+١٥٠',
    dailyRoutesLbl: 'مسارات يومية',
    happyRidersVal: '+٥٠ ألف',
    happyRidersLbl: 'راكب سعيد',
    vehiclesVal: '+٢٠٠',
    vehiclesLbl: 'حافلات',
    avgRatingVal: '⭐٤.٨',
    avgRatingLbl: 'متوسط التقييم',

    // How It Works
    simpleAndFast: 'سهل وسريع',
    howItWorksTitle: 'كيف نعمل',
    howItWorksDesc: 'انتقل من نقطة البداية إلى وجهتك في ثلاث خطوات بسيطة. بدون عناء، بدون قلق - رحلة سلسة وموثوقة.',
    step1Title: 'ابحث',
    step1Desc: 'أدخل نقطة الانطلاق والوجهة. سنعرض لك أفضل المسارات المتاحة مع أوقات الوصول المتوقعة.',
    step2Title: 'احجز',
    step2Desc: 'اختر رحلتك المفضلة وادفع بأمان من خلال نظام الدفع المتكامل Paymob. تأكيد فوري للحجز.',
    step3Title: 'اركب',
    step3Desc: 'تتبع حافلتك في الوقت الفعلي، اصعد متن الحافلة باستخدام تذكرتك الرقمية، واستمتع برحلة مريحة ومكيفة.',

    // Features
    whyDride: 'لماذا دي-رايد',
    builtForCairoStreets: 'الطريقة النخبوية للسفر',
    builtForCairoStreetsDesc: 'إعادة تعريف رحلتك بين القاهرة والإسكندرية. بدعم من ديستنيشن، يجمع دي-رايد بين السرعة والخصوصية والراحة الفائقة، وتتميز بمقاعد رغوة الذاكرة (ميموري فوم) وأمان معزز للارتقاء بكل ميل في رحلتك.',
    featureLiveTrackingTitle: 'تتبع مباشر',
    featureLiveTrackingDesc: 'راحة البال لك ولعائلتك. تضمن التحديثات في الوقت الفعلي أماناً تاماً طوال رحلتك.',
    featureMemoryFoamTitle: 'مقاعد ميموري فوم',
    featureMemoryFoamDesc: 'تجربة حصرية. مصممة لتوفير دعم متميز وراحة لا تضاهى، فقط في دي-رايد.',
    featureUsbTitle: 'منفذ USB',
    featureUsbDesc: 'ابق على اتصال. منفذ شحن مخصص لكل راكب لتزويد رحلتك بالطاقة.',
    featureSpaciousComfortTitle: 'راحة رحبة',
    featureSpaciousComfortDesc: 'مساحة إضافية للأرجل وأحزمة أمان معتمدة، مصممة لمنحك المساحة الشخصية التي تستحقها.',
    featureDashCamTitle: 'كاميرا لوحة القيادة',
    featureDashCamDesc: 'أمنكم هو أولويتنا. يتم مراقبة كل رحلة لضمان أعلى معايير السلامة.',

    // Partners
    trustedCollaborations: 'شراكات موثوقة',
    ourPartnersTitle: 'شركاؤنا',
    partnersSub: 'نعمل بالتعاون مع كبرى المؤسسات والجامعات وشبكات الدفع في مصر لتقديم رحلة متكاملة.',

    // Footer
    operatedBy: 'بواسطة ديستينيشن (Destination)',
    about: 'عن الخدمة',
    terms: 'الشروط والأحكام',
    privacy: 'سياسة الخصوصية',
    contact: 'اتصل بنا',
    allRightsReserved: '© ٢٠٢٦ دي-رايد. جميع الحقوق محفوظة.',

    // Auth Page - Login
    loginTitle: 'تسجيل الدخول إلى دي-رايد',
    loginSubtitle: 'أدخل بياناتك لإدارة رحلاتك وحجز مقاعدك.',
    loginEmailLabel: 'البريد الإلكتروني',
    loginEmailPlaceholder: 'مثال: ahmed@example.com',
    loginPasswordLabel: 'كلمة المرور',
    loginPasswordPlaceholder: '••••••••',
    loginBtn: 'تسجيل الدخول',
    loggingIn: 'جاري تسجيل الدخول بأمان...',
    dontHaveAccount: 'ليس لديك حساب؟',
    signUpNow: 'إنشاء حساب الآن',
    invalidCredentials: 'فشل تسجيل الدخول. يرجى التحقق من بياناتك.',

    // Auth Page - Register
    registerTitle: 'إنشاء حساب راكب جديد',
    registerSubtitle: 'انضم إلى شبكة حافلات الركاب المتميزة في مصر اليوم.',
    registerNameLabel: 'الاسم الكامل',
    registerNamePlaceholder: 'مثال: أحمد حسن',
    registerPhoneLabel: 'رقم الهاتف المحمول المصري',
    registerPhonePlaceholder: 'مثال: 01012345678',
    registerBtn: 'إنشاء حساب',
    registering: 'جاري إنشاء الحساب بأمان...',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    signInNow: 'تسجيل الدخول الآن',
    registerFailed: 'فشل التسجيل. يرجى التحقق من البيانات المدخلة.',
    phoneMustBe11: 'يجب أن يتكون رقم الهاتف المحمول المصري من ١١ رقماً بالضبط.',

    // Checkout Details & Page
    boardingAndDropoffTitle: 'نقاط الركوب والنزول',
    verifyStopsHelper: 'تحقق من نقاط الركوب والنزول المحددة أو اخترها. اضغط على الدبابيس لتعديلها.',
    showMapBtn: 'عرض الخريطة',
    selectManuallyBtn: 'تحديد يدوي',
    manualSelectionFallback: 'بديل التحديد اليدوي',
    manualSelectionFallbackDesc: 'اختر مراكز النقل الرئيسية في القاهرة لربطها بمسارك:',
    manualPickupHubLabel: 'نقطة الركوب اليدوية',
    manualDropoffHubLabel: 'نقطة النزول اليدوية',
    selectPickupOption: 'اختر نقطة الركوب',
    selectDropoffOption: 'اختر نقطة النزول',
    cabinLayoutTitle: 'توزيع المقاعد في حافلة تويوتا هايس',
    cabinLayoutDesc: 'اضغط على المقاعد المتاحة لاختيارها. المقاعد المقفلة مخصصة للحقائب.',
    hiaceModelLabel: 'تويوتا هايس L2H2',
    selectRequiredSeatsWarning: 'يرجى اختيار {count} مقاعد لتطابق طلب البحث الخاص بك.',
    confirmBookingBtn: 'تأكيد الحجز',
    configureCommuteStepper: 'تجهيز الرحلة',
    selectPaymentStepper: 'اختيار الدفع',
    confirmSeatStepper: 'تأكيد المقعد',
    loadingTripConfig: 'جاري تحميل تفاصيل الرحلة...',
    noTripSelected: 'لم يتم تحديد رحلة.',
    vipCockpitSeat: 'مقعد VIP أمامي ⭐',
    vipCockpitSeatDesc: 'مقعد في الصف الأمامي بجوار السائق مع رؤية ممتازة للطريق!',
    premiumWindowSeat: 'مقعد مميز بجوار النافذة 🪟',
    premiumWindowSeatDesc: 'مقعد بجانب النافذة يطل على الطريق.',
    rearWindowSeat: 'مقعد خلفي بجوار النافذة 🪟',
    rearWindowSeatDesc: 'مقعد مريح بجانب النافذة في الصف الأخير.',
    spaciousAisleSeat: 'مقعد ممر واسع 🚶',
    spaciousAisleSeatDesc: 'مقعد سهل الوصول يقع مباشرة على ممر الحافلة.',
    standardCabinSeat: 'مقعد كابينة قياسي 💺',
    standardCabinSeatDesc: 'مقعد ركاب مريح في وسط الحافلة.',
    luggageHoldAreaLocked: 'منطقة الحقائب (مغلقة بواسطة المسؤول)',
    seatOccupiedTitle: 'مقعد رقم {num} (محجوز)',
    seatTitle: 'مقعد رقم {num}',
    pleaseSelectSeatsToMatch: 'يرجى اختيار {count} مقاعد لتتطابق مع طلب البحث.',
    reservationFailed: 'فشل الحجز: ',
    closestPickupHighlighted: 'لقد حددنا أقرب نقطة ركوب إليك.',
    requestedSeatsLabel: 'المقاعد المطلوبة',
    requestedSeatsCountLabel: 'تم اختيار {count} من أصل {required}',
    dashboardLabel: 'لوحة التحكم',
    slidingDoorEntryLabel: 'باب ركوب منزلق',
    commuteDetailsLabel: 'تفاصيل الرحلة والذهاب',
    lineRouteLabel: 'خط المسار',
    localizedBoardingTimeLabel: 'وقت الصعود المحدد محلياً',
    notSelectedLabel: 'لم يتم الاختيار',
    bookingMultipleSeatsDesc: 'حجز مقاعد متعددة في عملية واحدة. سيتم إصدار جميع تذاكر الركوب معاً!',
    invoiceBreakdownLabel: 'تفاصيل الفاتورة والحساب',
    legSegmentLabel: 'قطاع الرحلة',
    startLabel: 'البداية',
    endLabel: 'النهاية',
    baseFareLabel: 'الأجرة الأساسية',
    bookingFeeLabel: 'رسوم الحجز',
    reservingSeatsLoading: 'جاري حجز المقاعد...',
    selectRequiredSeatsButton: 'يرجى تحديد {count} مقعد/مقاعد',
    confirmAndProceedBtn: 'التأكيد والمتابعة للدفع',
    seatsTemporaryHoldInfo: 'سيتم حجز المقاعد مؤقتاً لمدة ١٠ دقائق.',
    tripConfigNotFound: 'تفاصيل الرحلة غير متوفرة.',

    invalidMobileWalletNumber: 'يرجى إدخال رقم محفظة هاتف صحيح (مثال: 01012345678)',

    // Support Chat Widget
    supportHelpDesk: 'الدعم الفني دي-رايد',
    supportOnlineStatus: 'متاحين على مدار الساعة ٢٤/٧',
    supportLiveChatStatus: 'محادثة فورية مباشرة',
    supportTicketSelectionDesc: 'حدد تذكرة دعم حالية لبدء المحادثة المباشرة مع وكلائنا:',
    supportNoActiveTickets: 'لا توجد تذاكر دعم مفتوحة حالياً.',
    supportCreateTicketBtn: 'فتح تذكرة دعم جديدة',
    supportNeedNewTicketPrompt: 'هل تحتاج إلى فتح تذكرة جديدة؟',
    supportOriginalTicketCardHeader: 'تذكرة المشكلة الأساسية',
    supportStartChattingPlaceholder: 'ابدأ المحادثة! وكلاؤنا متصلون الآن.',
    supportTicketClosedResolved: 'هذه التذكرة مغلقة وحُلت.',
    supportTypeMessagePlaceholder: 'اكتب رسالة...',

    // TripSearch & Available Trips Page
    availableTrips: 'الرحلات المتاحة',
    smartSearchSubtitle: 'بحث ذكي: الركوب والنزول في حدود ٥ كم',
    next5days: 'الـ ٥ أيام القادمة',
    searchingRides: 'جاري البحث عن أفضل الرحلات...',
    noTripsFound: 'لم يتم العثور على رحلات',
    noTripsFoundDesc: 'لم نتمكن من العثور على أي رحلات مجدولة للتواريخ المحددة.',
    searchAnotherRoute: 'البحث عن مسار آخر',
    earliest: 'الأقرب مغادرة',
    cheapest: 'الأرخص سعراً',
    fewestWalks: 'الأقل سيراً',
    activeShuttle: 'حافلة نشطة',
    alternativeDate: 'تاريخ بديل',
    boardingStop: 'محطة الركوب',
    dropoffStop: 'محطة النزول',
    walksTotal: 'سير: {total} متر إجمالاً ({pickup} م للركوب · {dropoff} م للنزول)',
    seatsLeft: 'تبقت {count} مقاعد',
    bookSeatTicket: 'حجز مقعد 🎟️',
    routeStopsSelect: 'محطات الخط (اختر محطات)',
    pickup: 'ركوب',
    dropoff: 'نزول',
    noSearchParameters: 'لا توجد معايير بحث',
    noSearchParametersDesc: 'يرجى العودة واختيار مسار أو إدخال موقعك للبحث عن رحلات.',
    backToHome: 'العودة للرئيسية',

    // Payment Page Secure & Costs
    secureRidePayment: 'الدفع الآمن للرحلة',
    secureRidePaymentDesc: 'بوابة الدفع الآمنة للرحلات',
    selectPaymentMethod: 'اختر طريقة الدفع',
    pciDssHelper: 'جميع عمليات الدفع مشفرة بالكامل وتتوافق مع معايير الأمان PCI-DSS.',
    creditCardOptionTitle: 'بطاقة ائتمانية / بطاقة الخصم',
    creditCardOptionDesc: 'ادفع عبر الإنترنت فوراً باستخدام فيزا، ماستركارد، أو ميزة عبر بوابة بيموب الآمنة.',
    cashOptionTitle: 'الدفع نقداً عند الركوب',
    cashOptionDesc: 'ادفع نقداً مباشرة للسائق عند ركوب الحافلة. حجز التذكرة فوري في كل الأحوال.',
    securePaymobCheckout: 'بوابة دفع بيموب الآمنة',
    paymobRedirectionDisclaimer: 'سيتم توجيهك إلى صفحة بيموب الآمنة لإتمام عملية الدفع بالبطاقة.',
    supportedCardSchemes: 'البطاقات المدعومة: فيزا، ماستركارد، ميزة، والبطاقات الدولية.',
    cashOnBoardInstructions: 'يرجى تجهيز مبلغ {amount} ج.م بالضبط إن أمكن لتجنب التأخير عند الصعود.',
    reservationDossier: 'تفاصيل الحجز والملف',
    routeLineLabel: 'خط الرحلة',
    standardRoute: 'مسار قياسي',
    departureSchedule: 'جدول المغادرة',
    assignedSeats: 'المقاعد المخصصة',
    pickupHub: 'محطة الركوب',
    dropoffHub: 'محطة النزول',
    billingDetails: 'تفاصيل الحساب',
    seatReservationCost: 'حجز مقعد ({count})',
    vatIncluded: 'ضريبة القيمة المضافة (١٤٪ شاملة)',
    processingFee: 'رسوم المعالجة',
    freeProcessing: '٠.٠٠ ج.م (مجانياً)',
    totalCharge: 'المبلغ الإجمالي',
    encryptedOnlineCheckoutInfo: 'عمليات دفع مشفرة بالكامل. نقبل البطاقات والدفع نقداً.',
    bookingDetailsNotFound: 'تفاصيل الحجز غير متوفرة.',
    returnToHome: 'العودة للرئيسية',
    noBookingSelected: 'لم يتم تحديد أي حجز.',
    loadingBookingDetails: 'جاري تحميل تفاصيل الحجز...',
    verifyingPayment: 'جاري التحقق من عملية الدفع...',
    paymentSuccessful: 'تمت عملية الدفع بنجاح!',
    paymentSuccessDesc: 'تمت معالجة معاملتك وتأكيد حجز مقعدك.',
    viewMyTrips: 'عرض رحلاتي',
    paymentFailed: 'فشلت عملية الدفع',
    paymentFailedDesc: 'لم نتمكن من معالجة عملية الدفع الخاصة بك. يرجى المحاولة مرة أخرى.',
    paymentSuccessNotificationTitle: 'تم الدفع بنجاح ✅',
    paymentSuccessNotificationDesc: 'اكتملت معاملتك وتم تأمين مقعدك.',
    promoCodeLabel: 'الرمز الترويجي',
    applyPromoCode: 'تطبيق',
    removePromoCode: 'إزالة',
    promoCodeApplied: 'تم تطبيق الرمز الترويجي بنجاح!',
    promoCodeInvalid: 'رمز ترويجي غير صالح أو منتهي الصلاحية',
    promoDiscount: 'خصم ({code})',
    enterPromoCode: 'أدخل الرمز الترويجي...',
    
    // LiveTracking Page
    noVehicleSelected: 'لم يتم اختيار حافلة',
    selectTripToTrack: 'يرجى اختيار رحلة من حجوزاتك لتتبعها.',
    backToMyTrips: 'العودة إلى رحلاتي',
    activeGpsTracking: 'تتبع نشط للموقع',
    vehicleOffline: 'الحافلة غير متصلة بالإنترنت',
    statusScheduled: 'مجدولة',
    loadingRoute: 'جاري تحميل المسار...',
    scheduledDeparture: 'وقت المغادرة المجدول:',
    minibusDetailsWillUpdate: 'ستتحدث تفاصيل الحافلة قريباً. لم يبدأ السائق ببث الموقع الجغرافي المباشر بعد. يبدأ هذا عادة قبل ١٠-١٥ دقيقة من المغادرة عند فتح بوابات الصعود.',
    minibusOnRoute: 'الحافلة في طريقها. إحداثيات التتبع تُبث بسلاسة.',
    vehicleModel: 'طراز الحافلة:',
    licensePlate: 'لوحة الترخيص:',
    driverPartner: 'الشريك السائق:',
    callOperator: 'الاتصال بالمسؤول',
    supportChat: 'محادثة الدعم',
    supportTicketCreatedAlert: 'تم فتح تذكرة دعم. سيتصل بك وكيل دعم دي-رايد قريباً.',
    departureTerminal: 'محطة المغادرة',
    destinationStation: 'محطة الوصول',
    shuttleActiveLocation: 'الموقع النشط للحافلة',

    // Contact Page
    contactSupportHelpDeskBadge: 'الدعم ومكتب المساعدة',
    contactGetInTouch: 'تواصل معنا',
    contactSubtitle: 'هل لديك استفسارات حول الحجز، الدفع، أو المسارات؟ أرسل لنا رسالة وسيقوم فريقنا بالرد عليك قريباً.',
    contactEmailSupport: 'الدعم عبر البريد الإلكتروني',
    contactPhoneHotline: 'الخط الساخن للهاتف',
    contactHqLocation: 'المقر الرئيسي',
    contactHqLocationVal: 'القاهرة الجديدة، القاهرة، مصر',
    contactWorkingHours: 'ساعات العمل',
    contactWorkingHoursVal: 'عمليات ٢٤/٧ / مكتب الدعم',
    contactTicketSubmitted: 'تم إرسال التذكرة بنجاح!',
    contactTicketSuccessDesc: 'شكراً لتواصلك مع دي-رايد. تم تسجيل تذكرتك، وسيقوم فريقنا بمراجعتها والرد عليها قريباً.',
    contactSubmitAnother: 'إرسال تذكرة أخرى',
    contactOpenSupportTicket: 'فتح تذكرة دعم',
    contactDetailIssue: 'يرجى تفصيل مشكلتك وسيقوم وكيل الدعم بالمتابعة.',
    contactPassengerName: 'اسم الراكب',
    contactEmailAddress: 'البريد الإلكتروني',
    contactSubject: 'الموضوع',
    contactSubjectPlaceholder: 'مثال: مشكلة في تكرار خصم القيمة',
    contactMessageDetail: 'تفاصيل الرسالة',
    contactMessagePlaceholder: 'يرجى تقديم تفاصيل حول استفسارك أو مشكلتك...',
    contactSubmitTicketBtn: 'إرسال التذكرة',
    contactSubmitting: 'جاري الإرسال...',
    contactLoadingProfile: 'جاري تحميل الملف الشخصي...',
    contactFailedSubmit: 'فشل إرسال تذكرة الدعم.',

    // Routes Page
    routesCommuteNetworks: 'شبكات الركاب',
    routesExplorerTitle: 'مستكشف مسارات دي-رايد',
    routesExplorerDesc: 'تصفح خطوط النقل الثابتة، واعرض نقاط التحقق المخصصة، واطلع على الجداول الزمنية. اختر مساراً أدناه لعرض إحداثيات الطريق والمخطط الزمني.',
    routesLoading: 'جاري تحميل مسارات دي-رايد...',
    routesNoRegisteredTitle: 'لا توجد مسارات مسجلة',
    routesNoRegisteredDesc: 'لا توجد مسارات نقل نشطة حالياً في النظام. يرجى التحقق لاحقاً أو مراجعة المسؤول.',
    routesAvailableLines: 'الخطوط المتاحة ({count})',
    routesStartPrefix: '🟢 البداية:',
    routesEndPrefix: '🏁 النهاية:',
    routesNoTripsScheduled: 'لا توجد رحلات مجدولة',
    routesTripsScheduled: 'تمت جدولة {count} رحلات',
    routesBookShuttles: 'حجز الحافلات ←',
    routesDurationMins: 'رحلة مدتها {count} دقيقة',
    routesBookRideBtn: 'حجز الرحلة',
    routesInteractiveTrack: 'تتبع المسار التفاعلي',
    routesSnappedRoadways: 'إحداثيات الطرق المحددة (OSRM)',
    routesTimelineTitle: 'المخطط الزمني لتتابع نقاط التحقق',
    routesOriginTerminal: 'محطة البداية',
    routesFinalTerminal: 'محطة الوصول النهائية',
    routesStopNum: 'محطة رقم {num}',
    routesBuffer: 'وقت الانتظار',
    routesGeofence: 'السياج الجغرافي',
    routesComplianceTitle: 'الامتثال لقواعد النقل الجماعي في مصر:',
    routesComplianceDesc: 'تلتزم الحافلات بالانتظار طوال فترة الانتظار المحددة في كل نقطة تحقق. تُغلق بوابات الصعود تماماً عند انتهاء الوقت. تحقق دائماً من منطقة التحقق الجغرافي لتذكرتك عند الصعود.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('dride_lang') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('dride_lang', lang);
  };

  const isRtl = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRtl]);

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    let text = translations[language]?.[key] || translations['en']?.[key] || key;
    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
